### ISSUE TITLE
Configure connections in the gadget

### ISSUE THREAD

**Issue by farshidtz** [canonical/lora-basicstation-snap#16]
Since the model assertion lists the snaps, the connection can also be set in the [gadget](https://github.com/canonical/lora-basicstation-snap/blob/eaaf8bb9c90f672dbf98df2cdf5bc9408a4dc6c2/ubuntu-core-image/additions-to-gadget.yaml#L1):
```yaml
connections:
    # Needed to communicate with Docker over the Unix socket
    - slot: sLCsFAO8PKM5Z0fAKNszUOX0YASjQfeZ:docker-daemon
      plug: Ym43FmNEiZgqaAciYg6EMqRC4dUjcYYb:docker
    # Needed to use the docker CLI
    - slot: sLCsFAO8PKM5Z0fAKNszUOX0YASjQfeZ:docker-executables
      plug: Ym43FmNEiZgqaAciYg6EMqRC4dUjcYYb:docker-executables
```

And removed from [this landscape script](https://github.com/canonical/lora-basicstation-snap/blob/eaaf8bb9c90f672dbf98df2cdf5bc9408a4dc6c2/landscape/scripts/configure-lora-basicstation.sh#L6-L26).
